### ISSUE TITLE
Master Task List

### ISSUE THREAD

**Issue by hellsan631** [hellsan631/loopback-connector-aerospike#6]
Failed PersistedModel Hooks
- [ ] **Hook** ._find_ [expected [] to equal [ 'first' ]](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1006)
- [ ] **Hook** ._findOrCreate_ [expected 'hook not called' to equal {...}](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1018)
- [ ] **Hook** ._findOrCreate_ [expected {} to be an instance of ValidationError](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1028)
- [ ] **Hook** ._findOrCreate_ [expected [ 'access' ] to equal [ 'access', 'before save', 'after save' ]](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1032)
- [ ] **Hook** ._findOrCreate_ [expected [ null ] to equal [ [Error: test error] ]](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1045)
- [ ] **Hook** ._findOrCreate_ [expected 'hook not called' to equal {...}](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1057)
- [ ] **Hook** ._count_ [expected { count: 2 } to be 1](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1057)
- [ ] **Hook** ._prototype.save_ [expected {id: 3} _actual: {id: 1}_](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1071)
- [ ] **Hook** ._prototype.save_ Issue #9 "isNewInstance": _false vs [null]_
  - [ ] [Test: 9](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1099) 
  - [ ] [Test: 10](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1129)
- [ ] **Hook** ._prototype.updateAttributes_ update without providing the id is not supported
  - [ ] [Test: 11](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1159)
  - [ ] [Test: 12](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1165)
  - [ ] [Test: 13](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1171)
  - [ ] [Test: 14](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1177)
  - [ ] [Test: 15](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1195)
- [x] **Hook** ._updateOrCreate_ Object.keys called on non-object (PR: #11)
- [ ] **Hook** ._updateOrCreate_ [expected {id: 1} _actual: {id: 1433280395}_](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1201)
- [ ] **Hook** ._updateOrCreate_ [update without providing the id is not supported](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1245)
- [ ] **Hook** ._deleteAll_ Issue #9 AEROSPIKE_ERR_RECORD_NOT_FOUND
  - [ ] [Test: 26](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1281)
  - [ ] [Test: 27 (incorrect ID)](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1285)
  - [ ] [Test: 28](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1298)
  - [ ] [Test: 29 (incorrect ID)](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1302)
  - [ ] [Test: 30](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1315)
  - [ ] [Test: 31 (incorrect ID)](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1319)
  - [ ] [Test: 32 (incorrect ID)](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1332)
  - [ ] [Test: 33](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1345)
- [ ] **Hook** ._updateAll_ [update without providing the id is not supported](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1349)
- [ ] **Hook** ._updateAll_ [Key must be a string, we need advanced delete query support](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1353)
- [ ] **Hook** ._updateAll_ [update without providing the id is not supported](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1357)

**Comment by mattapperson** [comment]
destroy and destroy all are my current tasks... expect results by monday :)

**Comment by hellsan631** [comment]
Simple Methods
- [x] Connect (PR: #4)
- [x] Disconnect (b31bcfff464c5b99a52ed8d280bfddf686c5635a)
- [x] Ping (PR: #4)
- [x] Exists (0fad44ada97707da6edac79e285a0f41c0d774a4)
- [x] Count (0fad44ada97707da6edac79e285a0f41c0d774a4)

Crud
- [x] Create (PR: #5 )
- [x] Find (PR: #10)
- [x] UpdateOrCreate (PR: #10)
- [x] UpdateAll (PR: #10)
- [x] UpdateAttributes (PR: #10)
- [x] Save (PR: #10)
- [x] Destroy (PR: #7)
- [x] DestroyAll (PR: #7)

**Comment by hellsan631** [comment]
- [x] **Hook** ._updateOrCreate_ Object.keys called on non-object (PR: #11)
  - [x] [Test: 16](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1201)
  - [x] [Test: 17](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1206)
  - [x] [Test: 20](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1251)
  - [x] [Test: 21](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1256)
  - [x] [Test: 22](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1261)
  - [x] [Test: 23](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1266)
  - [x] [Test: 24](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1271)
  - [x] [Test: 25](https://travis-ci.org/hellsan631/loopback-connector-aerospike/builds/65153017#L1276)
